'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'am'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

// Full translations for the owner portal
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.rooms': 'Rooms',
    'nav.tenants': 'Tenants',
    'nav.payments': 'Payments',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.signout': 'Sign out',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.total_rooms': 'Total Rooms',
    'dashboard.occupied': 'Occupied',
    'dashboard.available': 'Available',
    'dashboard.unpaid_rents': 'Unpaid Rents',
    'dashboard.recent_payments': 'Recent Payments',
    'dashboard.no_payments': 'No payments recorded yet.',
    'dashboard.tenant': 'Tenant',
    'dashboard.room': 'Room',
    'dashboard.amount': 'Amount',
    'dashboard.date': 'Date',
    'dashboard.status': 'Status',
    'dashboard.unpaid_tenants': 'Tenants with Unpaid Rent',
    'dashboard.due_day': 'Due: Day',
    'dashboard.send_sms': 'Send SMS',
    'dashboard.close': 'Close',
    'dashboard.no_unpaid': 'All tenants are up to date!',
    'dashboard.unpaid_modal_title': 'Unpaid Tenants This Month',
    'dashboard.all_paid': 'All tenants have paid this month!',
    'dashboard.due': 'Due Day:',
    'dashboard.call': 'Call',
    'dashboard.send_reminder': 'Send Reminder',
    'dashboard.sending': 'Sending...',

    // Rooms
    'rooms.title': 'Rooms',
    'rooms.title_singular': 'Room',
    'rooms.add': 'Add Room',
    'rooms.room_number': 'Room No.',
    'rooms.building': 'Building',
    'rooms.floor': 'Floor / Type',
    'rooms.rent': 'Monthly Rent',
    'rooms.status': 'Status',
    'rooms.actions': 'Actions',
    'rooms.available': 'Available',
    'rooms.occupied': 'Occupied',
    'rooms.no_rooms': 'No rooms found.',
    'rooms.number': 'Room Number',
    'rooms.type': 'Room Type',
    'rooms.type_office': 'Office',
    'rooms.type_shop': 'Shop',
    'rooms.type_single': 'Single',
    'rooms.type_double': 'Double',
    'rooms.type_studio': 'Studio',
    'rooms.type_apartment': 'Apartment',
    'rooms.rent_birr': 'Monthly Rent (Birr)',
    'rooms.description': 'Description',
    'rooms.desc_placeholder': 'Optional description...',
    'rooms.add_title': 'Add New Room',
    'rooms.add_success': 'Room Added',
    'rooms.added_in': 'Room successfully added to',
    'rooms.edit_title': 'Edit Room',
    'rooms.edit_success': 'Room Updated',
    'rooms.updated': 'Room information has been updated.',
    'rooms.done': 'Done',
    'rooms.cancel': 'Cancel',
    'rooms.save': 'Save Changes',
    'rooms.saving': 'Saving...',
    'rooms.processing': 'Processing...',
    'rooms.delete': 'Delete Room',
    'rooms.confirm_delete': 'Are you sure you want to delete this room? This cannot be undone.',
    'rooms.status_available': 'Available',
    'rooms.status_occupied': 'Occupied',
    'rooms.status_maintenance': 'Under Maintenance',
    'rooms.floor_type': 'Floor / Type',
    'rooms.floor_abbr': 'Floor',
    'rooms.type_default': 'N/A',
    'rooms.single_room': 'Single Room',
    'rooms.bulk_add': 'Bulk Add',
    'rooms.how_many': 'How many rooms?',
    'rooms.generate_table': 'Generate Edit Table',
    'rooms.remove': 'Remove',
    'rooms.add_row': '+ Add Row',

    // Tenants
    'tenants.title': 'Tenants',
    'tenants.add': 'Add Tenant',
    'tenants.name': 'Full Name',
    'tenants.phone': 'Phone',
    'tenants.id': 'ID Number',
    'tenants.joined': 'Joined',
    'tenants.actions': 'Actions',
    'tenants.manage': 'Manage',
    'tenants.no_tenants': 'No tenants found.',
    'tenants.register': 'Register New Tenant & Lease',
    'tenants.success': 'Tenant Registered Successfully',
    'tenants.info_section': '1. Tenant Information',
    'tenants.lease_section': '2. Lease Details',
    'tenants.full_name': 'Full Name',
    'tenants.phone_number': 'Phone Number',
    'tenants.id_passport': 'ID / Passport Number',
    'tenants.select_room': 'Select Room',
    'tenants.no_rooms': 'No rooms available. Please add rooms first.',
    'tenants.start_date': 'Lease Start Date (Ethiopian)',
    'tenants.end_date': 'End Date (Optional)',
    'tenants.monthly_rent': 'Monthly Rent (Birr)',
    'tenants.due_day': 'Rent Due Day (1-30)',
    'tenants.cancel': 'Cancel',
    'tenants.register_btn': 'Register Tenant & Lease',
    'tenants.processing': 'Processing...',
    'tenants.done': 'Done',
    'tenants.record_created': 'Tenant record created and lease agreement activated.',
    'tenants.choose_room': 'Choose an available room...',
    'tenants.manage_title': 'Manage Tenant Details',
    'tenants.manage_success': 'Tenant Updated Successfully',
    'tenants.updated': 'Tenant information has been updated.',
    'tenants.notes': 'Notes',
    'tenants.notes_placeholder': 'Internal notes about the tenant...',
    'tenants.save': 'Save Changes',
    'tenants.saving': 'Saving...',
    'tenants.danger_zone': 'Danger Zone',
    'tenants.active_lease': 'Active Lease Found',
    'tenants.end_lease_desc': 'End the lease to make the room available again.',
    'tenants.end_lease': 'End Lease',
    'tenants.confirm_end_lease': 'Are you sure you want to end this lease? The room will become available.',
    'tenants.note_update': 'Note: To update tenant personal details, fill out the form below.',

    // Payments
    'payments.title': 'Payments',
    'payments.add': 'Record Payment',
    'payments.date': 'Date',
    'payments.tenant_room': 'Tenant / Room',
    'payments.amount': 'Amount',
    'payments.method': 'Method / Tx ID',
    'payments.method_txid': 'Method / Tx ID',
    'payments.payment_details': 'Payment Receipt',
    'payments.unassigned_tenant': 'Unassigned Tenant',
    'payments.amount_birr': 'Amount (Birr)',
    'payments.status': 'Status',
    'payments.actions': 'Actions',
    'payments.details': 'Details',
    'payments.no_payments': 'No payments recorded yet.',
    'payments.verified': 'Verified',
    'payments.pending': 'Pending',
    'payments.unassigned': 'Unassigned',
    'payments.detail_title': 'Payment Receipt',
    'payments.close': 'Close',
    'payments.paid_by': 'Paid By',
    'payments.amount_paid': 'Amount Paid',
    'payments.payment_date': 'Payment Date',
    'payments.add_title': 'Record New Payment',
    'payments.select_tenant': 'Select Tenant / Lease',
    'payments.choose_tenant': 'Choose a tenant...',
    'payments.months_to_pay': 'Months to Pay',
    'payments.total_amount': 'Total Amount (Birr)',
    'payments.payment_method': 'Payment Method',
    'payments.bank': 'Bank Transfer',
    'payments.telebirr': 'Telebirr',
    'payments.cash': 'Cash',
    'payments.transaction_id': 'Transaction ID (optional)',
    'payments.note': 'Note (optional)',
    'payments.submit': 'Record Payment',
    'payments.submitting': 'Recording...',
    'payments.success': 'Payment Recorded',
    'payments.success_desc': 'Payment has been recorded successfully.',
    'payments.txid': 'Transaction ID',
    'payments.select_tenant_first': 'Select a tenant first...',
    'payments.save_payment': 'Record Payment',
    'payments.recording': 'Recording...',
    'payments.1_month': '1 Month',
    'payments.3_months': '3 Months',
    'payments.6_months': '6 Months',
    'payments.add_success': 'Payment Recorded',
    'payments.added_message': 'Payment recorded and is pending verification.',
    'payments.date_eth': 'Payment Date (Ethiopian)',
    'payments.multi_month_group': 'months paid',
    'payments.expand': 'Show months',
    'payments.collapse': 'Hide months',
    'rooms.assigned_room': 'Assigned Room',
    'common.optional': 'Optional',

    // Reports
    'reports.title': 'Reports',
    'reports.occupancy': 'Occupancy Rate',
    'reports.monthly_income': 'Monthly Income (Verified)',
    'reports.total_tenants': 'Total Active Tenants',
    'reports.pending_payments': 'Pending Payments',
    'reports.rooms_occupied': 'rooms occupied',
    'reports.out_of': 'out of',
    'reports.total': 'total',
    'reports.unpaid_tenants': 'Unpaid Tenants',
    'reports.income_chart': 'Income vs. Expected Rent Chart',

    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile Settings',
    'settings.name': 'Full Name',
    'settings.email': 'Email Address',
    'settings.phone': 'Phone Number',
    'settings.save_profile': 'Save Profile',
    'settings.saving': 'Saving...',
    'settings.password': 'Change Password',
    'settings.current_password': 'Current Password',
    'settings.new_password': 'New Password',
    'settings.confirm_password': 'Confirm New Password',
    'settings.change_password': 'Change Password',

    // Common
    'common.loading': 'Loading...',
    'common.cancel': 'Cancel',
    'common.save': 'Save Changes',
    'common.saving': 'Saving...',
    'common.done': 'Done',
    'common.close': 'Close',
    'common.error': 'Something went wrong.',
    'common.birr': 'Birr',
    'common.1_month': '1 Month (Default)',
    'common.3_months': '3 Months',
    'common.6_months': '6 Months',
    'settings.profile_title': 'Profile Settings',
    'settings.profile_subtitle': 'Update your personal information',
    'settings.security_title': 'Security',
    'settings.security_subtitle': 'Change your password',
    'settings.update_password': 'Update Password',
    'settings.updating': 'Updating...',
    'settings.profile_success': 'Profile updated successfully',
    'settings.profile_error': 'Failed to update profile',
    'settings.password_success': 'Password updated. Signing you out in 2 seconds...',
    'settings.password_error': 'Failed to update password',
    'tenants.email': 'Email',
  },
  am: {
    // Nav
    'nav.dashboard': 'ዳሽቦርድ',
    'nav.rooms': 'ክፍሎች',
    'nav.tenants': 'ተከራዮች',
    'nav.payments': 'ክፍያዎች',
    'nav.reports': 'ሪፖርቶች',
    'nav.settings': 'ቅንብሮች',
    'nav.signout': 'ውጣ',

    // Dashboard
    'dashboard.title': 'ዋና ዳሽቦርድ',
    'dashboard.total_rooms': 'ጠቅላላ ክፍሎች',
    'dashboard.occupied': 'የተያዙ',
    'dashboard.available': 'ያሉ',
    'dashboard.unpaid_rents': 'ያልተከፈሉ ኪራዮች',
    'dashboard.recent_payments': 'የቅርብ ጊዜ ክፍያዎች',
    'dashboard.no_payments': 'ምንም ክፍያ አልተመዘገበም።',
    'dashboard.tenant': 'ተከራይ',
    'dashboard.room': 'ክፍል',
    'dashboard.amount': 'መጠን',
    'dashboard.date': 'ቀን',
    'dashboard.status': 'ሁኔታ',
    'dashboard.unpaid_tenants': 'ያልከፈሉ ተከራዮች',
    'dashboard.due_day': 'የክፍያ ቀን',
    'dashboard.send_sms': 'ኤስኤምኤስ ላክ',
    'dashboard.close': 'ዝጋ',
    'dashboard.no_unpaid': 'ሁሉም ተከራዮች ክፍያ ፈፅመዋል!',
    'dashboard.unpaid_modal_title': 'በዚህ ወር ያልከፈሉ ተከራዮች',
    'dashboard.all_paid': 'ሁሉም ተከራዮች በዚህ ወር ከፍለዋል!',
    'dashboard.due': 'የክፍያ ቀን:',
    'dashboard.call': 'ደወል',
    'dashboard.send_reminder': 'ማስታወሻ ላክ',
    'dashboard.sending': 'እየተላከ...',

    // Rooms
    'rooms.title': 'ክፍሎች',
    'rooms.title_singular': 'ክፍል',
    'rooms.add': 'ክፍል ጨምር',
    'rooms.room_number': 'የክፍል ቁጥር',
    'rooms.building': 'ህንፃ',
    'rooms.floor': 'ፎቅ / አይነት',
    'rooms.rent': 'ወርሃዊ ኪራይ',
    'rooms.status': 'ሁኔታ',
    'rooms.actions': 'ድርጊቶች',
    'rooms.available': 'ተኪ',
    'rooms.occupied': 'የተያዘ',
    'rooms.no_rooms': 'ምንም ክፍሎች አልተገኙም።',
    'rooms.number': 'የክፍል ቁጥር',
    'rooms.type': 'የክፍል አይነት',
    'rooms.type_office': 'ቢሮ',
    'rooms.type_shop': 'ሱቅ',
    'rooms.type_single': 'ነጠላ',
    'rooms.type_double': 'ድርብ',
    'rooms.type_studio': 'ስቱዲዮ',
    'rooms.type_apartment': 'አፓርትመንት',
    'rooms.rent_birr': 'ወርሃዊ ኪራይ (ብር)',
    'rooms.description': 'መግለጫ',
    'rooms.desc_placeholder': 'አማራጭ መግለጫ...',
    'rooms.add_title': 'አዲስ ክፍል ጨምር',
    'rooms.add_success': 'ክፍል ተጨምሯል',
    'rooms.added_in': 'ክፍል በተሳካ ሁኔታ ተጨምሯል',
    'rooms.edit_title': 'ክፍል አርትዕ',
    'rooms.edit_success': 'ክፍል ተዘምኗል',
    'rooms.updated': 'የክፍሉ መረጃ ተዘምኗል።',
    'rooms.done': 'ተጠናቋል',
    'rooms.cancel': 'ሰርዝ',
    'rooms.save': 'ለውጦች አስቀምጥ',
    'rooms.saving': 'በሂደት...',
    'rooms.processing': 'በሂደት ላይ...',
    'rooms.delete': 'ክፍል ዘግ',
    'rooms.confirm_delete': 'ይህን ክፍል ማጥፋት እርግጠኛ ነዎት? ይህ ቀልብሱ አይችልም።',
    'rooms.status_available': 'ተኪ',
    'rooms.status_occupied': 'የተያዘ',
    'rooms.status_maintenance': 'በጥገና ላይ',
    'rooms.floor_type': 'ፎቅ / አይነት',
    'rooms.floor_abbr': 'ፎቅ',
    'rooms.type_default': 'ሌላ',
    'rooms.single_room': 'አንድ ክፍል',
    'rooms.bulk_add': 'በብዛት ጨምር',
    'rooms.how_many': 'ስንት ክፍሎች?',
    'rooms.generate_table': 'ሰንጠረዥ ፍጠር',
    'rooms.remove': 'አስወግድ',
    'rooms.add_row': '+ ተጨማሪ ተርታ',

    // Tenants
    'tenants.title': 'ተከራዮች',
    'tenants.add': 'ተከራይ ጨምር',
    'tenants.name': 'ሙሉ ስም',
    'tenants.phone': 'ስልክ',
    'tenants.id': 'መታወቂያ ቁጥር',
    'tenants.joined': 'የተቀላቀለበት',
    'tenants.actions': 'ድርጊቶች',
    'tenants.manage': 'አስተዳድር',
    'tenants.no_tenants': 'ምንም ተከራዮች አልተገኙም።',
    'tenants.register': 'አዲስ ተከራይ እና ውል ምዝግብ',
    'tenants.success': 'ተከራይ በተሳካ ሁኔታ ተመዝግቧል',
    'tenants.info_section': '1. የተከራይ መረጃ',
    'tenants.lease_section': '2. የኪራይ ውል ዝርዝር',
    'tenants.full_name': 'ሙሉ ስም',
    'tenants.phone_number': 'ስልክ ቁጥር',
    'tenants.id_passport': 'መታወቂያ / ፓስፖርት ቁጥር',
    'tenants.select_room': 'ክፍል ምረጥ',
    'tenants.no_rooms': 'ምንም ክፍሎች የሉም። እባክዎ አስቀድመው ክፍሎችን ይጨምሩ።',
    'tenants.start_date': 'የኪራይ ጅምር ቀን (ኢትዮጵያ)',
    'tenants.end_date': 'የማብቂያ ቀን (አማራጭ)',
    'tenants.monthly_rent': 'ወርሃዊ ኪራይ (ብር)',
    'tenants.due_day': 'የኪራይ ክፍያ ቀን (1-30)',
    'tenants.cancel': 'ሰርዝ',
    'tenants.register_btn': 'ተከራይና ውል ምዝግብ',
    'tenants.processing': 'በሂደት ላይ...',
    'tenants.done': 'ተጠናቋል',
    'tenants.record_created': 'የተከራዩ መዝገብ ተፈጥሯል እና የኪራይ ውሉ ተሰጥቷል።',
    'tenants.choose_room': 'ክፍል ይምረጡ...',
    'tenants.manage_title': 'የተከራይ ዝርዝር አስተዳድር',
    'tenants.manage_success': 'የተከራዩ መረጃ ተዘምኗል',
    'tenants.updated': 'የተከራዩ መረጃ ተዘምኗል።',
    'tenants.notes': 'ማስታወሻዎች',
    'tenants.notes_placeholder': 'ስለ ተከራዩ ውስጣዊ ማስታወሻ...',
    'tenants.save': 'ለውጦች አስቀምጥ',
    'tenants.saving': 'በሂደት...',
    'tenants.danger_zone': 'አደገኛ ዞን',
    'tenants.active_lease': 'ንቁ ውል ተገኝቷል',
    'tenants.end_lease_desc': 'ክፍሉ እንደገና ሊሞሉ ውሉን ያቁሙ።',
    'tenants.end_lease': 'ውሉን አቁም',
    'tenants.confirm_end_lease': 'ይህን ኪራይ ውል ማቆም እርግጠኛ ነዎት? ክፍሉ ነፃ ይሆናል።',
    'tenants.note_update': 'ማሳሰቢያ: የተከራዩን ዝርዝር ለማዘመን፣ ከታች ያለውን ቅጽ ይሙሉ።',

    // Payments
    'payments.title': 'ክፍያዎች',
    'payments.add': 'ክፍያ ምዝግብ',
    'payments.date': 'ቀን',
    'payments.tenant_room': 'ተከራይ / ክፍል',
    'payments.amount': 'መጠን',
    'payments.method': 'ዘዴ / ስእምት',
    'payments.method_txid': 'ዘዴ / ስእምት',
    'payments.payment_details': 'የክፍያ ደረሰኝ',
    'payments.unassigned_tenant': 'ያልተሰጠ ተከራይ',
    'payments.amount_birr': 'መጠን (ብር)',
    'payments.status': 'ሁኔታ',
    'payments.actions': 'ድርጊቶች',
    'payments.details': 'ዝርዝር',
    'payments.no_payments': 'ምንም ክፍያ አልተመዘገበም።',
    'payments.verified': 'ተረጋግጧል',
    'payments.pending': 'በጥበቃ',
    'payments.unassigned': 'ያልተመደበ',
    'payments.detail_title': 'የክፍያ ደረሰኝ',
    'payments.close': 'ዝጋ',
    'payments.paid_by': 'የከፈለ',
    'payments.amount_paid': 'የተከፈለ መጠን',
    'payments.payment_date': 'የክፍያ ቀን',
    'payments.add_title': 'አዲስ ክፍያ ምዝግብ',
    'payments.select_tenant': 'ተከራይ / ኪራይ ምረጥ',
    'payments.choose_tenant': 'ተከራይ ምረጥ...',
    'payments.months_to_pay': 'የሚከፈሉ ወሮች',
    'payments.total_amount': 'ጠቅላላ መጠን (ብር)',
    'payments.payment_method': 'የክፍያ ዘዴ',
    'payments.bank': 'የባንክ ማስተላለፊያ',
    'payments.telebirr': 'ቴሌብር',
    'payments.cash': 'ጥሬ ገንዘብ',
    'payments.transaction_id': 'ትራንዛክሽን መታወቂያ (አማራጭ)',
    'payments.note': 'ማስታወሻ (አማራጭ)',
    'payments.submit': 'ክፍያ ምዝግብ',
    'payments.submitting': 'በሂደት ላይ...',
    'payments.success': 'ክፍያ ተመዝግቧል',
    'payments.success_desc': 'ክፍያ በተሳካ ሁኔታ ተመዝግቧል።',
    'payments.txid': 'የትራንዛክሽን መታወቂያ',
    'payments.select_tenant_first': 'በቅድሚያ ተከራይ ይምረጡ...',
    'payments.save_payment': 'ክፍያ መዝግብ',
    'payments.recording': 'በመመዝገብ ላይ...',
    'payments.1_month': '1 ወር',
    'payments.3_months': '3 ወራት',
    'payments.6_months': '6 ወራት',
    'payments.add_success': 'ክፍያ ተመዝግቧል',
    'payments.added_message': 'ክፍያ ተመዝግቧል እና ማረጋገጫ በመጠባበቅ ላይ ነው።',
    'payments.date_eth': 'የክፍያ ቀን (በኢትዮጵያ)',
    'payments.multi_month_group': 'ወራት ተከፍለዋል',
    'payments.expand': 'ወራትን አሳይ',
    'payments.collapse': 'ወራትን ደብቅ',
    'rooms.assigned_room': 'የተመደበው ክፍል',
    'common.optional': 'አማራጭ',

    // Reports
    'reports.title': 'ሪፖርቶች',
    'reports.occupancy': 'የክፍፍል ደረጃ',
    'reports.monthly_income': 'ወርሃዊ ገቢ (የተረጋገጠ)',
    'reports.total_tenants': 'ጠቅላላ ንቁ ተከራዮች',
    'reports.pending_payments': 'በጥበቃ ያሉ ክፍያዎች',
    'reports.rooms_occupied': 'ክፍሎች ተይዘዋል',
    'reports.out_of': 'ከ',
    'reports.total': 'ጠቅላላ',
    'reports.unpaid_tenants': 'ያልከፈሉ ተከራዮች',
    'reports.income_chart': 'ገቢ እና የሚጠበቅ ኪራይ ገበታ',

    // Settings
    'settings.title': 'ቅንብሮች',
    'settings.profile': 'የፕሮፋይል ቅንብሮች',
    'settings.name': 'ሙሉ ስም',
    'settings.email': 'ኢሜይል አድራሻ',
    'settings.phone': 'ስልክ ቁጥር',
    'settings.save_profile': 'ፕሮፋይል አስቀምጥ',
    'settings.saving': 'በሂደት...',
    'settings.password': 'የይለፍ ቃል ቀይር',
    'settings.current_password': 'አሁን ያለ የይለፍ ቃል',
    'settings.new_password': 'አዲስ የይለፍ ቃል',
    'settings.confirm_password': 'አዲስ የይለፍ ቃል አረጋግጥ',
    'settings.change_password': 'የይለፍ ቃል ቀይር',

    // Common
    'common.loading': 'በሂደት ላይ...',
    'common.cancel': 'ሰርዝ',
    'common.save': 'ለውጦች አስቀምጥ',
    'common.saving': 'በሂደት...',
    'common.done': 'ተጠናቋል',
    'common.close': 'ዝጋ',
    'common.error': 'ስህተት ተፈጥሯል።',
    'common.birr': 'ብር',
    'common.1_month': '1 ወር (ነባሪ)',
    'common.3_months': '3 ወሮች',
    'common.6_months': '6 ወሮች',
    'settings.profile_title': 'የፕሮፋይል ቅንብሮች',
    'settings.profile_subtitle': 'የግል መረጃዎን ያዘምኑ',
    'settings.security_title': 'ደህንነት',
    'settings.security_subtitle': 'የይለፍ ቃልዎን ይቀይሩ',
    'settings.update_password': 'የይለፍ ቃል አዘምን',
    'settings.updating': 'እያዘመነ...',
    'settings.profile_success': 'ፕሮፋይል ተዘምኗል',
    'settings.profile_error': 'ፕሮፋይልን ማዘምን አልተቻለም',
    'settings.password_success': 'የይለፍ ቃል ተዘምኗል። ከ2 ሰርዓት ውጣ...',
    'settings.password_error': 'የይለፍ ቃልን ማዘምን አልተቻለም',
    'tenants.email': 'ኢሜይል',
  }
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'am',
  setLanguage: () => {},
  t: (key) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('am')

  useEffect(() => {
    const saved = localStorage.getItem('owner_lang_pref') as Language
    if (saved === 'en' || saved === 'am') setLanguageState(saved)
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('owner_lang_pref', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
